#!/anaconda3/bin/python3

import os
import json
from calculateAverageResponseFunction import calculateAverageResponseFunction

# Print the system specs in the log file
os.system('cat /proc/cpuinfo')

# Set initial Flywheel paths
flywheel_base ='/flywheel/v0/'
manifest_file = os.path.join(flywheel_base, 'manifest.json')
config_path = os.path.join(flywheel_base, 'config.json')
first_output_dir = '/firstOutput' # Working in the flywheel output folder might cause issues so creating a first level output folder 
os.system('mkdir %s'%first_output_dir)
final_output_dir = os.path.join(flywheel_base, 'output')

# Set paths to the tools 
mrtrix_path = '/mrtrix3/bin/' #path to mrtrix bin
###################Parse Config Here###########################################

with open(config_path) as config_file:
    job_config = json.load(config_file)

config = job_config['config']
shell = config['shell']

################### Input Files ###############################################

dwi_list = []
bvec_list = []
bval_list = []

for i in range(45):
    image_number = i+1  
    if image_number < 10: 
        image_number_string = '0' + str(image_number)
    else:
        image_number_string = str(image_number)  

    image_path_and_name = os.path.join(flywheel_base, 'input', 'dwiImage%s' % image_number_string) 
    
    if os.path.exists(image_path_and_name):
        main_image = os.path.join(image_path_and_name, os.listdir(image_path_and_name)[0])
        if os.path.split(main_image)[1][-4:] == '.zip':
            os.system('unzip -j %s */All_DTI_acqs/data/bvecs -d %s' % (main_image, image_path_and_name))
            os.system('unzip -j %s */All_DTI_acqs/data/bvals -d %s' % (main_image, image_path_and_name))            
            os.system('unzip -j %s */All_DTI_acqs/data/data.nii.gz -d %s' % (main_image, image_path_and_name))
            data = os.path.join(image_path_and_name, 'data.nii.gz')
            bval = os.path.join(image_path_and_name, 'bvals')
            bvec = os.path.join(image_path_and_name,  'bvecs')                      
            dwi_list.append(data)    
            bvec_list.append(bvec)
            bval_list.append(bval)       
        else:
            dwi_list.append(main_image)

#################### Process #################################################

calculateAverageResponseFunction(mrtrix_path, dwi_list, bval_list, bvec_list, first_output_dir, final_output_dir, shell)
