#!/anaconda3/bin/python3

import os
import json
from roi_tractography import roi_tractography

# Print the system specs in the log file
os.system('cat /proc/cpuinfo')

# Set initial Flywheel paths
flywheel_base ='/flywheel/v0/'
manifest_file = os.path.join(flywheel_base, 'manifest.json')
config_path = os.path.join(flywheel_base, 'config.json')
first_output_dir = '/firstOutput' # Working in the flywheel output folder might cause issues so creating a first level output folder 
os.system('mkdir %s'%first_output_dir)
final_output_dir = os.path.join(flywheel_base, 'output')

# Set paths to the tools 
trekker_bin = '/trekker/build/bin/Linux/' #path to trekker

###################Parse Config Here###########################################

with open(config_path) as config_file:
    job_config = json.load(config_file)

config = job_config['config']

directionality = config['directionality']
timeLimit = config['timeLimit']
minLength = config['minLength']
maxLength = config['maxLength']
minFODamp = config['minFODamp']
seed_count = config['seed_count']
atMaxLength = config['atMaxLength']
minRadiusOfCurvature = config['minRadiusOfCurvature']
probeCount = config['probeCount']
outputFileName = config['outputFileName']

################### Input Files ###############################################

# paths to inputs
FOD_image_path = os.path.join(flywheel_base, 'input/FOD_image')
seed_image_path = os.path.join(flywheel_base, 'input/seed_image')
ROI_mask_path = os.path.join(flywheel_base, 'input/ROI_mask')

# Get input files 
FOD_image = os.path.join(FOD_image_path, os.listdir(FOD_image_path)[0])
seed_image = os.path.join(seed_image_path, os.listdir(seed_image_path)[0])
ROI_mask = os.path.join(ROI_mask_path, os.listdir(ROI_mask_path)[0])

#################### Process #################################################
final_steamline_file_path = os.path.join(final_output_dir, outputFileName + '.vtk') 
final_plot_path = os.path.join(final_output_dir, outputFileName + '.png') 

roi_tractography(FOD_image, seed_image, ROI_mask, final_steamline_file_path, final_plot_path, trekker_bin, 
                 directionality, timeLimit, minLength, maxLength, minFODamp, 
                 seed_count, atMaxLength, minRadiusOfCurvature, probeCount)
